## Evo 2 Yarrowia Sparse Auto Encoder (Local Version)

This notebook shows a **minimal, class‑free** workflow to:

1. **Load Yarrowia** sequence from a local FASTA (`GCF_001761485.1_ASM176148v1_genomic.fna`) and annotations from a local **GFF** (`genomic.gff`).
2. Use a **local Evo2 model** (via `transformers`) to get layer activations.
3. Load a pre‑trained **Top‑K tied Sparse Autoencoder (SAE)** from Hugging Face.
4. **Project activations into SAE features** and **plot a handful** of them with GFF annotations.

> [!TIP]
> **Setup:** Install dependencies with `pip install -U transformers huggingface_hub evo2 biopython flash-attn` and restart your kernel.
> This notebook defaults to the **7B model** which is compatible with the provided SAE weights.

### Set up imports

In [10]:
import os, io, base64, json, zipfile, time, yaml, pkgutil, gc, os
import numpy as np
import torch
import matplotlib.pyplot as plt
import glob
from Bio import SeqIO
from huggingface_hub import hf_hub_download
# from transformers import AutoModelForCausalLM, AutoTokenizer
import pandas as pd
from functools import partial
from evo2.models import Evo2
from vortex.model.model import StripedHyena
from vortex.model.utils import dotdict

# Reproducibility & device
torch.manual_seed(42)
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"
dtype = torch.bfloat16  # works well for large tensors
torch.set_grad_enabled(False)

print("Device:", device)

Device: cuda

### Load Yarrowia sequence (first 25,000 bases of chromosome 1)

In [ ]:
FASTA_PATH = "/home/jacobbw/Desktop/Code/yarrowia_language_modeling/yarrowia_notebooks/sparce_autoencoder/GCF_001761485.1_ASM176148v1_genomic.fna"   # FASTA
GFF_PATH   = "genomic.gff"                               # GFF annotations

WINDOW_START = 1            # 1-based
WINDOW_END   = 25_000       # inclusive 1..25000

def pick_chr1_record(fasta_path):
    """Return the SeqRecord for chromosome 1 (best effort).
    If not found, return the first record.
    """
    candidates = []
    for rec in SeqIO.parse(fasta_path, "fasta"):
        rid = (rec.id + " " + (rec.description or "")).lower()
        candidates.append(rec)
        if any(tag in rid for tag in ["chromosome 1", "chromosome i", "chr1", "chr 1"]):
            return rec
    # fallback: first record
    return candidates[0]

chr1_rec = pick_chr1_record(FASTA_PATH)
seq_1based = chr1_rec.seq[WINDOW_START-1:WINDOW_END]
sequence = str(seq_1based)
print(chr1_rec.id, "length:", len(chr1_rec.seq))
print("Window length:", len(sequence))
print(sequence[:80] + " ...")

### Load Evo2 helper functions

In [3]:
# === CONFIG ===
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.allow_tf32 = True
CHECKPOINT_PATH = "/home/jacobbw/roell_group/hf_cache/evo2_40b.pt"
SAE_LAYER_NAME = "blocks.26.mlp.l3"
WANTED_LAYERS = [SAE_LAYER_NAME]
USE_MULTI_GPU = True
COMPILE_MODEL = False
def evo2_forward(sequence, output_layers, model=None, device="cuda:0"):
    if model is None:
        raise ValueError("Must pass the loaded model_obj")
    actual_model = model.model if hasattr(model, 'model') else model
    from vortex.model.tokenizer import CharLevelTokenizer
    tokenizer = CharLevelTokenizer(vocab_size=512)
    input_ids = tokenizer.tokenize(sequence)
    input_ids = torch.tensor([input_ids], dtype=torch.long, device="cuda:0")
    acts = {}
    hooks = []
    def get_hook(name):
        def hook(module, input, output):
            data = output[0] if isinstance(output, tuple) else output
            acts[f"{name}.output"] = data.detach().float().cpu().numpy()
        return hook
    for layer_name in output_layers:
        try:
            module = actual_model
            for part in layer_name.split('.'):
                module = module[int(part)] if part.isdigit() else getattr(module, part)
            hooks.append(module.register_forward_hook(get_hook(layer_name)))
        except Exception as e:
            print(f"Warning: Could not register hook for {layer_name}: {e}")
    with torch.no_grad(), torch.amp.autocast('cuda', dtype=torch.bfloat16):
        logits = actual_model(input_ids)
        logits = logits[0] if isinstance(logits, tuple) else logits
        lgt = logits.detach().float().cpu().numpy()
    for h in hooks:
        h.remove()
    def squeeze(x):
        return x[0] if (isinstance(x, np.ndarray) and x.ndim >= 3 and x.shape[0] == 1) else x
    return squeeze(lgt), {k: squeeze(v) for k, v in acts.items()}
def nuke_fp8(model):
    for module in model.modules():
        if hasattr(module, 'fp8_meta'):
            module.fp8_meta = {"fp8_checkpoint": False}
        if hasattr(module, 'fp8'):
            module.fp8 = False
        if hasattr(module, 'fp8_calibration'):
            module.fp8_calibration = False
def load_state_dict_streaming(model, state_dict, device):
    model_state = model.state_dict()
    for key in model_state.keys():
        if key in state_dict:
            param = state_dict[key]
            if param.dtype != torch.bfloat16:
                param = param.to(dtype=torch.bfloat16)
            model_state[key].copy_(param.to(device=device, non_blocking=True))
    torch.cuda.synchronize()
def load_evo2_blazing_fast():
    print("=" * 60)
    print("🚀 BLAZING FAST EVO2 LOADER")
    print("=" * 60)
    num_gpus = torch.cuda.device_count()
    print(f"Found {num_gpus} GPU(s): {[torch.cuda.get_device_name(i) for i in range(num_gpus)]}")
    primary_device = torch.device("cuda:0")
    torch.cuda.set_device(primary_device)
    
    print("\n[1/5] Loading config...")
    config_data = pkgutil.get_data("evo2", "configs/evo2-40b-1m.yml")
    config = dotdict(yaml.safe_load(config_data))
    
    print("\n[2/5] Initializing model skeleton on GPU...")
    model = StripedHyena(config)
    model = model.to(device=primary_device, dtype=torch.bfloat16)
    print(f"   Model structure allocated: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")
    
    print("\n[3/5] Patching FP8...")
    nuke_fp8(model)
    
    print("\n[4/5] Streaming weights from disk → GPU...")
    state_dict = torch.load(CHECKPOINT_PATH, map_location="cpu", mmap=True, weights_only=False)
    if "state_dict" in state_dict:
        state_dict = state_dict["state_dict"]
    fp8_keys = [k for k in state_dict.keys() if "_extra_state" in k]
    for k in fp8_keys:
        del state_dict[k]
    print(f"   Filtered {len(fp8_keys)} FP8 metadata keys")
    load_state_dict_streaming(model, state_dict, primary_device)
    del state_dict
    gc.collect()
    torch.cuda.empty_cache()
    print(f"   Post-load VRAM: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")
    
    if USE_MULTI_GPU and num_gpus >= 2:
        print("\n[5/5] Splitting model across GPUs...")
        if hasattr(model, 'blocks'):
            n_layers = len(model.blocks)
            n_gpus = min(num_gpus, 4)  # Use up to 4 GPUs
            layers_per_gpu = n_layers // n_gpus
        
            for i, block in enumerate(model.blocks):
                gpu_id = min(i // layers_per_gpu, n_gpus - 1)
                block.to(torch.device(f"cuda:{gpu_id}"))
        
            print(f"   Split {n_layers} layers across {n_gpus} GPUs")
            print(f"   ~{layers_per_gpu} layers per GPU")
    else:
        print("\n[5/5] Single GPU mode")
    
    if COMPILE_MODEL:
        print("\n[BONUS] Compiling model...")
        try:
            model = torch.compile(model, mode="reduce-overhead", fullgraph=False)
            print("   ✓ Compiled")
        except Exception as e:
            print(f"   ✗ Compile failed: {e}")
    
    model.eval()
    wrapper = Evo2.__new__(Evo2)
    wrapper.model = model
    wrapper.tokenizer = None
    print("\n" + "=" * 60)
    print("✅ MODEL READY")
    print(f"   GPU 0: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")
    if num_gpus >= 2:
        print(f"   GPU 1: {torch.cuda.memory_allocated(1)/1024**3:.2f} GB")
    print("=" * 60)
    return wrapper
print("✓ Functions defined")

✓ Functions defined

### Load the model

In [4]:
model_obj = load_evo2_blazing_fast()

============================================================
🚀 BLAZING FAST EVO2 LOADER
============================================================
Found 2 GPU(s): ['NVIDIA H200 NVL', 'NVIDIA H200 NVL']

[1/5] Loading config...

[2/5] Initializing model skeleton on GPU...

[01/16/26 00:28:27] INFO     StripedHyena - INFO - Initializing StripedHyena with config:              ]8;id=810191;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=74514;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#616\616]8;;\
                             {'model_name': 'shc-evo2-40b-8k-11T-v2', 'vocab_size': 512,
                             'hidden_size': 8192, 'num_filters': 8192, 'hcl_layer_idxs': [2, 6, 9, 13,
                             16, 20, 23, 27, 30, 34, 38, 41, 45, 48], 'hcm_layer_idxs': [1, 5, 8, 12,
                             15, 19, 22, 26, 29, 33, 37, 40, 44, 47], 'hcs_layer_idxs': [0, 4, 7, 11,
                             14, 18, 21, 25, 28, 32, 36, 39, 43, 46], 'attn_layer_idxs': [3, 10, 17,
                             24, 31, 35, 42, 49], 'hcm_filter_length': 128, 'hcl_filter_groups': 8192,
                             'hcm_filter_groups': 512, 'hcs_filter_groups': 512, 'hcs_filter_length':
                             7, 'num_layers': 50, 'short_filter_length': 3, 'num_attention_heads': 64,
                             'short_filter_bias': False, 'mlp_init_method': 'torch.nn.init.zeros_',
                             'mlp_output_init_method': 'torch.nn.init.zeros_', 'eps': 1e-06,
                             'state_size': 16, 'rotary_emb_base': 1000000,
                             'rotary_emb_scaling_factor': 128, 'use_interpolated_rotary_pos_emb':
                             True, 'make_vocab_size_divisible_by': 8, 'inner_size_multiple_of': 128,
                             'inner_mlp_size': 22528, 'log_intermediate_values': False, 'proj_groups':
                             1, 'hyena_filter_groups': 1, 'column_split_hyena': False, 'column_split':
                             True, 'interleave': True, 'evo2_style_activations': True,
                             'use_fp8_input_projections': True, 'model_parallel_size': 1,
                             'pipe_parallel_size': 1, 'tie_embeddings': True, 'mha_out_proj_bias':
                             True, 'hyena_out_proj_bias': True, 'hyena_flip_x1x2': False,
                             'qkv_proj_bias': False, 'max_seqlen': 1048576, 'max_batch_size': 1,
                             'final_norm': True, 'use_flash_attn': True, 'use_flash_rmsnorm': False,
                             'use_flash_depthwise': False, 'use_flashfft': False,
                             'use_laughing_hyena': False, 'inference_mode': True, 'tokenizer_type':
                             'CharLevelTokenizer', 'prefill_style': 'fft', 'mlp_activation': 'gelu',
                             'print_activations': False}

                    INFO     StripedHyena - INFO - Initializing 50 blocks...                           ]8;id=611657;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=156978;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#635\635]8;;\

                    INFO     StripedHyena - INFO - Distributing across 2 GPUs, approximately 25 layers ]8;id=355075;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=825941;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#642\642]8;;\
                             per GPU

  0%|                                                                                                                                       | 0/50 [00:00<?, ?it/s]

                    INFO     StripedHyena - INFO - Assigned layer_idx=0 to device='cuda:0'             ]8;id=675708;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=264498;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 0: 822185472              ]8;id=404424;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=729145;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=1 to device='cuda:0'             ]8;id=31110;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=773532;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 1: 822255616              ]8;id=843731;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=606260;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

  4%|█████                                                                                                                          | 2/50 [00:00<00:02, 19.72it/s]

                    INFO     StripedHyena - INFO - Assigned layer_idx=2 to device='cuda:0'             ]8;id=409493;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=325408;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 2: 822452224              ]8;id=458118;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=901040;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=3 to device='cuda:0'             ]8;id=475487;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=85155;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 3: 822108160              ]8;id=924349;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=480750;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

  8%|██████████▏                                                                                                                    | 4/50 [00:00<00:02, 17.38it/s]

                    INFO     StripedHyena - INFO - Assigned layer_idx=4 to device='cuda:0'             ]8;id=96811;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=416954;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 4: 822185472              ]8;id=790153;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=953971;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=5 to device='cuda:0'             ]8;id=614365;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=60416;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 5: 822255616              ]8;id=292797;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=394618;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=6 to device='cuda:0'             ]8;id=984390;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=37345;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 6: 822452224              ]8;id=149492;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=797811;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=7 to device='cuda:0'             ]8;id=744017;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=410;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 7: 822185472              ]8;id=980353;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=353907;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=8 to device='cuda:0'             ]8;id=200549;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=376044;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 8: 822255616              ]8;id=824535;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=584476;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=9 to device='cuda:0'             ]8;id=531528;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=867369;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 9: 822452224              ]8;id=768977;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=970720;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=10 to device='cuda:0'            ]8;id=491290;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=826046;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 10: 822108160             ]8;id=207432;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=910012;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=11 to device='cuda:0'            ]8;id=576355;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=837024;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 11: 822185472             ]8;id=856347;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=480554;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=12 to device='cuda:0'            ]8;id=736529;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=176277;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 12: 822255616             ]8;id=705349;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=441305;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=13 to device='cuda:0'            ]8;id=538762;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=232201;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 13: 822452224             ]8;id=723606;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=566786;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=14 to device='cuda:0'            ]8;id=647139;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=779219;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 14: 822185472             ]8;id=721178;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=988262;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=15 to device='cuda:0'            ]8;id=855782;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=338524;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 15: 822255616             ]8;id=729112;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=159085;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=16 to device='cuda:0'            ]8;id=307067;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=373826;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 16: 822452224             ]8;id=321637;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=702964;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=17 to device='cuda:0'            ]8;id=663810;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=882641;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 17: 822108160             ]8;id=120551;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=592367;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=18 to device='cuda:0'            ]8;id=173287;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=457897;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 18: 822185472             ]8;id=768572;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=829785;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=19 to device='cuda:0'            ]8;id=894200;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=927365;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 19: 822255616             ]8;id=978836;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=467554;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=20 to device='cuda:0'            ]8;id=849603;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=187167;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 20: 822452224             ]8;id=589998;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=55748;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=21 to device='cuda:0'            ]8;id=749657;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=80570;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 21: 822185472             ]8;id=969876;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=458833;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=22 to device='cuda:0'            ]8;id=533992;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=181074;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 22: 822255616             ]8;id=250033;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=57909;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=23 to device='cuda:0'            ]8;id=948267;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=327008;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 23: 822452224             ]8;id=166887;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=693483;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=24 to device='cuda:0'            ]8;id=846071;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=471751;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 24: 822108160             ]8;id=217421;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=354653;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

 50%|███████████████████████████████████████████████████████████████                                                               | 25/50 [00:00<00:00, 96.80it/s]

                    INFO     StripedHyena - INFO - Assigned layer_idx=25 to device='cuda:1'            ]8;id=626916;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=817233;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 25: 822185472             ]8;id=976688;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=805761;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=26 to device='cuda:1'            ]8;id=542899;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=745041;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 26: 822255616             ]8;id=751455;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=431226;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=27 to device='cuda:1'            ]8;id=969074;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=989689;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 27: 822452224             ]8;id=635483;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=628820;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=28 to device='cuda:1'            ]8;id=391735;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=130184;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 28: 822185472             ]8;id=66622;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=6076;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=29 to device='cuda:1'            ]8;id=396336;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=654947;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 29: 822255616             ]8;id=848921;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=128536;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=30 to device='cuda:1'            ]8;id=12506;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=727377;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 30: 822452224             ]8;id=237688;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=677188;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=31 to device='cuda:1'            ]8;id=502241;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=419506;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 31: 822108160             ]8;id=636965;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=863779;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=32 to device='cuda:1'            ]8;id=550090;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=648659;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 32: 822185472             ]8;id=138381;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=489367;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=33 to device='cuda:1'            ]8;id=365301;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=266442;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 33: 822255616             ]8;id=789907;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=759191;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=34 to device='cuda:1'            ]8;id=219313;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=843090;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 34: 822452224             ]8;id=142750;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=14629;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=35 to device='cuda:1'            ]8;id=143818;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=15163;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 35: 822108160             ]8;id=834847;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=885691;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

 72%|██████████████████████████████████████████████████████████████████████████████████████████▋                                   | 36/50 [00:00<00:00, 62.38it/s]

                    INFO     StripedHyena - INFO - Assigned layer_idx=36 to device='cuda:1'            ]8;id=823962;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=923537;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 36: 822185472             ]8;id=935831;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=636413;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=37 to device='cuda:1'            ]8;id=71572;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=789220;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 37: 822255616             ]8;id=887623;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=415883;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=38 to device='cuda:1'            ]8;id=381683;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=786532;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 38: 822452224             ]8;id=737072;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=586865;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=39 to device='cuda:1'            ]8;id=326980;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=360583;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 39: 822185472             ]8;id=66728;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=710239;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=40 to device='cuda:1'            ]8;id=265074;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=806696;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 40: 822255616             ]8;id=461505;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=314911;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=41 to device='cuda:1'            ]8;id=165;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=93387;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 41: 822452224             ]8;id=429605;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=341245;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=42 to device='cuda:1'            ]8;id=734216;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=891589;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 42: 822108160             ]8;id=361570;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=477565;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=43 to device='cuda:1'            ]8;id=829381;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=911466;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 43: 822185472             ]8;id=103147;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=750897;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=44 to device='cuda:1'            ]8;id=316424;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=9641;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 44: 822255616             ]8;id=353486;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=185003;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=45 to device='cuda:1'            ]8;id=365810;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=435159;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 45: 822452224             ]8;id=736425;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=40285;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=46 to device='cuda:1'            ]8;id=115261;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=268163;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 46: 822185472             ]8;id=591931;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=157679;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=47 to device='cuda:1'            ]8;id=292232;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=219257;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

[01/16/26 00:28:28] INFO     StripedHyena - INFO - Parameter count for block 47: 822255616             ]8;id=782821;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=773003;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=48 to device='cuda:1'            ]8;id=109667;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=642513;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 48: 822452224             ]8;id=567581;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=42603;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

                    INFO     StripedHyena - INFO - Assigned layer_idx=49 to device='cuda:1'            ]8;id=237520;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=84099;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#660\660]8;;\

                    INFO     StripedHyena - INFO - Parameter count for block 49: 822108160             ]8;id=28755;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=613955;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#661\661]8;;\

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 74.66it/s]

                    INFO     StripedHyena - INFO - Initialized model                                   ]8;id=974416;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py\model.py]8;;\:]8;id=674564;file:///root/evo2_admin_fix/lib/python3.12/site-packages/vortex/model/model.py#680\680]8;;\

   Model structure allocated: 76.59 GB

[3/5] Patching FP8...

[4/5] Streaming weights from disk → GPU...
   Filtered 258 FP8 metadata keys
   Post-load VRAM: 76.59 GB

[5/5] Splitting model across GPUs...
   Split 50 layers across 2 GPUs
   ~25 layers per GPU

============================================================
✅ MODEL READY
   GPU 0: 38.30 GB
   GPU 1: 38.29 GB
============================================================

## Training cells the SAE for 40b (skip this if already ran once)

In [5]:
SAE_CONFIG = {
    "d_in": 8192,              # evo2_40b hidden dim
    "expansion_factor": 8,      # 8192 * 8 = 65536 SAE hidden dim
    "k": 64,                    # Top-K sparsity
    "lr": 1e-4,
    "batch_size": 4096,         # tokens per batch
    "num_tokens": 100_000_000,  # 100M tokens total (adjust based on time)
    "save_every": 10_000_000,   # checkpoint every 10M tokens
}
SAE_LAYER = "blocks.26.mlp.l3"  # Layer to train SAE on
SAE_SAVE_PATH = "/home/jacobbw/roell_group/sae_40b_layer26.pt"

#### SAE Model Definition

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
class TopKSAE(nn.Module):
    def __init__(self, d_in, expansion_factor=8, k=64):
        super().__init__()
        self.d_in = d_in
        self.d_hidden = d_in * expansion_factor
        self.k = k
        
        # Encoder: d_in -> d_hidden
        self.W = nn.Parameter(torch.empty(d_in, self.d_hidden))
        self.b_enc = nn.Parameter(torch.zeros(self.d_hidden))
        
        # Decoder bias
        self.b_dec = nn.Parameter(torch.zeros(d_in))
        
        # Initialize weights
        nn.init.kaiming_uniform_(self.W)
        
    def encode(self, x):
        # x: [batch, d_in]
        pre_act = x @ self.W + self.b_enc  # [batch, d_hidden]
        post_act = F.relu(pre_act)
        
        # Top-K sparsity
        topk_values, topk_indices = torch.topk(post_act, k=self.k, dim=-1)
        sparse = torch.zeros_like(post_act)
        sparse.scatter_(dim=-1, index=topk_indices, src=topk_values)
        return sparse
    
    def decode(self, f):
        # f: [batch, d_hidden] (sparse)
        return f @ self.W.T + self.b_dec
    
    def forward(self, x):
        f = self.encode(x)
        x_hat = self.decode(f)
        return x_hat, f
# Initialize SAE
sae = TopKSAE(
    d_in=SAE_CONFIG["d_in"],
    expansion_factor=SAE_CONFIG["expansion_factor"],
    k=SAE_CONFIG["k"]
).to(device=device, dtype=torch.float32)  # Train in fp32 for stability
optimizer = torch.optim.Adam(sae.parameters(), lr=SAE_CONFIG["lr"])
print(f"SAE params: {sum(p.numel() for p in sae.parameters()):,}")
print(f"W shape: {sae.W.shape}")

SAE params: 536,944,640
W shape: torch.Size([8192, 65536])

#### Data Generator (streams activations from genomic data)

In [7]:
from pathlib import Path
def activation_generator(fasta_path, model_obj, layer_name, chunk_size=8192):
    '''
    Generator that yields batches of activations from the model.
    Processes the genome in chunks to avoid memory issues.
    '''
    from vortex.model.tokenizer import CharLevelTokenizer
    tokenizer = CharLevelTokenizer(vocab_size=512)
    
    # Parse FASTA
    records = list(SeqIO.parse(fasta_path, "fasta"))
    
    for rec in records:
        seq = str(rec.seq).upper()
        
        # Process in chunks
        for start in range(0, len(seq) - chunk_size, chunk_size // 2):  # 50% overlap
            chunk = seq[start:start + chunk_size]
            
            # Skip if contains too many Ns
            if chunk.count('N') > len(chunk) * 0.1:
                continue
            
            # Tokenize
            input_ids = tokenizer.tokenize(chunk)
            input_ids = torch.tensor([input_ids], dtype=torch.long, device="cuda:0")
            
            # Get activations via hook
            acts = {}
            def hook(module, inp, out):
                data = out[0] if isinstance(out, tuple) else out
                acts["data"] = data.detach()
            
            # Find the layer
            actual_model = model_obj.model if hasattr(model_obj, 'model') else model_obj
            module = actual_model
            for part in layer_name.split('.'):
                module = module[int(part)] if part.isdigit() else getattr(module, part)
            
            handle = module.register_forward_hook(hook)
            
            with torch.no_grad(), torch.amp.autocast('cuda', dtype=torch.bfloat16):
                _ = actual_model(input_ids)
            
            handle.remove()
            
            # Yield activations [seq_len, d_model]
            yield acts["data"].squeeze(0).float()
print("Activation generator defined")

Activation generator defined

#### Training Loop

In [8]:
import time
from tqdm import tqdm
def train_sae(sae, model_obj, fasta_path, config):
    sae.train()
    
    total_tokens = 0
    total_loss = 0
    batch_losses = []
    
    activation_buffer = []
    batch_size = config["batch_size"]
    
    pbar = tqdm(total=config["num_tokens"], desc="Training SAE")
    start_time = time.time()
    
    for act_batch in activation_generator(fasta_path, model_obj, SAE_LAYER):
        # act_batch: [seq_len, d_in]
        activation_buffer.append(act_batch.to(device))
        
        # When buffer is big enough, train
        buffer_tokens = sum(a.shape[0] for a in activation_buffer)
        
        if buffer_tokens >= batch_size:
            # Concatenate and shuffle
            all_acts = torch.cat(activation_buffer, dim=0)
            perm = torch.randperm(all_acts.shape[0])
            all_acts = all_acts[perm]
            
            # Train on mini-batches
            for i in range(0, len(all_acts) - batch_size, batch_size):
                batch = all_acts[i:i+batch_size].float()  # Convert to float32
                
                optimizer.zero_grad()
                
                x_hat, f_sparse = sae(batch)
                
                # Reconstruction loss
                loss = F.mse_loss(x_hat, batch)
                
                loss.backward()
                optimizer.step()
                
                total_loss += loss.item()
                batch_losses.append(loss.item())
                total_tokens += batch_size
                pbar.update(batch_size)
                
                if total_tokens % 1_000_000 == 0:
                    avg_loss = sum(batch_losses[-100:]) / len(batch_losses[-100:])
                    elapsed = time.time() - start_time
                    tokens_per_sec = total_tokens / elapsed
                    pbar.set_postfix({
                        "loss": f"{avg_loss:.4f}",
                        "tok/s": f"{tokens_per_sec:.0f}"
                    })
                
                # Save checkpoint
                if total_tokens % config["save_every"] == 0:
                    torch.save({
                        "W": sae.W.data,
                        "b_enc": sae.b_enc.data,
                        "b_dec": sae.b_dec.data,
                        "total_tokens": total_tokens,
                    }, SAE_SAVE_PATH.replace(".pt", f"_ckpt_{total_tokens//1_000_000}M.pt"))
                    print(f"\\nSaved checkpoint at {total_tokens:,} tokens")
                
                if total_tokens >= config["num_tokens"]:
                    break
            
            activation_buffer = []
        
        if total_tokens >= config["num_tokens"]:
            break
    
    pbar.close()
    
    # Final save
    torch.save({
        "W": sae.W.data,
        "b_enc": sae.b_enc.data,
        "b_dec": sae.b_dec.data,
        "total_tokens": total_tokens,
    }, SAE_SAVE_PATH)
    print(f"\\nTraining complete! Saved to {SAE_SAVE_PATH}")
    print(f"Total tokens: {total_tokens:,}")
    print(f"Final avg loss: {sum(batch_losses[-100:]) / len(batch_losses[-100:]):.4f}")
print("Training function defined")

Training function defined

#### Start Training

In [11]:
ckpts = sorted(glob.glob("/home/jacobbw/roell_group/sae_40b_layer26_ckpt_*.pt"))
if ckpts:
    latest = torch.load(ckpts[-1], map_location="cpu", weights_only=True)
    sae.W.data = latest["W"].to(device).float()
    sae.b_enc.data = latest["b_enc"].to(device).float()
    sae.b_dec.data = latest["b_dec"].to(device).float()
    print(f"✓ Resuming from checkpoint: {ckpts[-1]}")
    print(f"  Already trained on {latest['total_tokens']:,} tokens")
else:
    print("✓ Starting fresh training")
# Enable gradients and train
torch.set_grad_enabled(True)
train_sae(sae, model_obj, FASTA_PATH, SAE_CONFIG)

✓ Starting fresh training

Training SAE:  20%|███████████████████                                                                          | 20467712/100000000 [2:09:09<8:21:52, 2641.14it/s]

\nTraining complete! Saved to /home/jacobbw/roell_group/sae_40b_layer26.pt
Total tokens: 20,467,712
Final avg loss: 0.0000

In [12]:
state = torch.load("/home/jacobbw/roell_group/sae_40b_layer26.pt", map_location="cpu", weights_only=True)
W = state["W"].to(device=device, dtype=dtype)
b_enc = state["b_enc"].to(device=device, dtype=dtype)
b_dec = state["b_dec"].to(device=device, dtype=dtype)
print(f"Loaded SAE trained on {state['total_tokens']:,} tokens")
print(f"W shape: {W.shape}")  # Should be [8192, 65536]

Loaded SAE trained on 20,467,712 tokens
W shape: torch.Size([8192, 65536])

### Run INterface

In [13]:
print("Warmup run...")
with torch.no_grad(), torch.amp.autocast('cuda', dtype=torch.bfloat16):
    _ = model_obj.model(torch.zeros(1, 1024, dtype=torch.long, device="cuda:0"))
print("\nActual inference...")
with torch.no_grad(), torch.amp.autocast('cuda', dtype=torch.bfloat16):
    logits, acts = evo2_forward(sequence, output_layers=WANTED_LAYERS, model=model_obj)
print("Layers returned:", list(acts.keys()))
if f"{SAE_LAYER_NAME}.output" in acts:
    print("Activations shape:", acts[f"{SAE_LAYER_NAME}.output"].shape)

Warmup run...

Actual inference...
Layers returned: ['blocks.26.mlp.l3.output']
Activations shape: (25000, 8192)

### Inspect the activation vectors at the output of layer 26

In [14]:
# Extract the layer activations
layer_act = acts[f"{SAE_LAYER_NAME}.output"]
print(f'There are {len(layer_act)} tokens in this sequence window.')
print(f'Each token has {layer_act.shape[1]} features. This is the model hidden size or model dimension.')
# make a dataframe of this data
df = pd.DataFrame(layer_act, columns=[f'feature_{i}' for i in range(layer_act.shape[1])])
df.insert(0, 'base', list(sequence))
df.insert(0, 'position', range(WINDOW_START, WINDOW_END + 1))
df.head(10)

There are 25000 tokens in this sequence window.
Each token has 8192 features. This is the model hidden size or model dimension.

,position,base,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_8182,feature_8183,feature_8184,feature_8185,feature_8186,feature_8187,feature_8188,feature_8189,feature_8190,feature_8191
0,1,A,7.638334e-13,1.691092e-12,1.278977e-13,7.247536e-13,-1.243450e-13,1.513456e-12,9.379164e-13,-1.222134e-12,...,-7.851497e-13,-1.222134e-12,2.302158e-12,-8.562040e-13,5.471179e-13,1.989520e-12,1.087130e-12,1.904255e-12,6.821210e-13,1.371347e-12
1,2,G,9.592327e-13,2.103206e-12,1.652012e-13,9.023893e-13,-1.403322e-13,1.890044e-12,1.165290e-12,-1.513456e-12,...,-9.734435e-13,-1.534772e-12,2.884804e-12,-1.065814e-12,6.892265e-13,2.486900e-12,1.357137e-12,2.387424e-12,8.597567e-13,1.733724e-12
2,3,T,1.158185e-12,2.557954e-12,1.900702e-13,1.101341e-12,-1.803002e-13,2.287948e-12,1.413980e-12,-1.833200e-12,...,-1.186606e-12,-1.861622e-12,3.495870e-12,-1.278977e-12,8.348877e-13,2.998490e-12,1.634248e-12,2.884804e-12,1.037392e-12,2.088996e-12
3,4,C,1.264766e-12,2.771117e-12,2.122746e-13,1.207923e-12,-1.811884e-13,2.486900e-12,1.527667e-12,-1.975309e-12,...,-1.286082e-12,-1.989520e-12,3.751666e-12,-1.392664e-12,9.059420e-13,3.240075e-12,1.762146e-12,3.126388e-12,1.101341e-12,2.245315e-12
4,5,T,1.122658e-12,2.501110e-12,1.820766e-13,1.065814e-12,-1.776357e-13,2.231104e-12,1.378453e-12,-1.783462e-12,...,-1.151079e-12,-1.818989e-12,3.410605e-12,-1.243450e-12,8.135714e-13,2.927436e-12,1.591616e-12,2.813749e-12,1.023182e-12,2.046363e-12
5,6,G,1.115552e-12,2.458478e-12,1.847411e-13,1.058709e-12,-1.669775e-13,2.202682e-12,1.357137e-12,-1.755041e-12,...,-1.136868e-12,-1.783462e-12,3.353762e-12,-1.229239e-12,8.029133e-13,2.884804e-12,1.570299e-12,2.771117e-12,9.947598e-13,2.003731e-12
6,7,G,1.094236e-12,2.401634e-12,1.865175e-13,1.037392e-12,-1.643130e-13,2.160050e-12,1.335820e-12,-1.733724e-12,...,-1.115552e-12,-1.747935e-12,3.282707e-12,-1.215028e-12,7.851497e-13,2.827960e-12,1.541878e-12,2.714273e-12,9.734435e-13,1.961098e-12
7,8,T,1.151079e-12,2.543743e-12,1.900702e-13,1.094236e-12,-1.758593e-13,2.273737e-12,1.406875e-12,-1.818989e-12,...,-1.179501e-12,-1.847411e-12,3.481659e-12,-1.271871e-12,8.313350e-13,2.984279e-12,1.627143e-12,2.870593e-12,1.037392e-12,2.088996e-12
8,9,T,1.172396e-12,2.586376e-12,1.936229e-13,1.115552e-12,-1.776357e-13,2.316369e-12,1.428191e-12,-1.847411e-12,...,-1.193712e-12,-1.861622e-12,3.510081e-12,-1.293188e-12,8.419931e-13,3.026912e-12,1.648459e-12,2.913225e-12,1.037392e-12,2.103206e-12
9,10,T,1.172396e-12,2.572165e-12,1.953993e-13,1.108447e-12,-1.785239e-13,2.302158e-12,1.428191e-12,-1.847411e-12,...,-1.193712e-12,-1.875833e-12,3.510081e-12,-1.293188e-12,8.419931e-13,3.026912e-12,1.648459e-12,2.913225e-12,1.044498e-12,2.103206e-12

### Load the Top‑K tied SAE model from from Hugging Face
https://huggingface.co/Goodfire/Evo-2-Layer-26-Mixed

In [15]:
# Load YOUR trained SAE for evo2_40b
SAE_PATH = "/home/jacobbw/roell_group/sae_40b_layer26.pt"
state = torch.load(SAE_PATH, map_location="cpu", weights_only=True)
W = state["W"].to(device=device, dtype=dtype)
b_enc = state["b_enc"].to(device=device, dtype=dtype)
b_dec = state["b_dec"].to(device=device, dtype=dtype)
TOP_K = 64
print(f"Loaded SAE trained on {state['total_tokens']:,} tokens")
print("W:", tuple(W.shape))
print("b_enc:", tuple(b_enc.shape))
print("b_dec:", tuple(b_dec.shape))

Loaded SAE trained on 20,467,712 tokens
W: (8192, 65536)
b_enc: (65536,)
b_dec: (8192,)

### Define function for running the model (encode/decode helpers)

In [16]:
def relu(x):
    return torch.maximum(x, torch.zeros_like(x))

def encode_topk(x, W, b_enc, k=TOP_K):
    """x: [T, d_in]; returns sparse features f: [T, d_hidden_expanded] with Top‑K per row."""
    # Pre-activation
    f = x @ W + b_enc                  # [T, d_hidden_expanded]
    f = relu(f)

    # Top‑K per row
    # values, idx: [T, k]
    values, idx = torch.topk(f, k=min(k, f.shape[-1]), dim=-1)
    out = torch.zeros_like(f)
    out.scatter_(dim=-1, index=idx, src=values)
    return out

def decode(f, W, b_dec):
    return f @ W.T + b_dec

### Project Evo2 activations through the SAE

In [17]:
# Convert layer_act (numpy) -> torch
x = torch.tensor(layer_act, device=device, dtype=dtype)   # [T, d_in]

print(f'The input to the SAE has shape: {x.shape}')
print(f'The SAE weight (W) has shape: {W.shape}')

if x.shape[1] != W.shape[0]:
    print("\n" + "="*40)
    print("DIMENSION MISMATCH ERROR")
    print(f"Model activations (dim {x.shape[1]}) do not match SAE weights (dim {W.shape[0]}).")
    print("To fix this, ensure you are using 'arcinstitute/evo2_7b'.")
    print("="*40 + "\n")
else:
    with torch.no_grad():
        f_sparse = encode_topk(x, W, b_enc, k=TOP_K)          # [T, d_hidden_expanded]

    # Convert sparse features to numpy for further analysis
    sae_acts = f_sparse.float().cpu().numpy()
    print(f'The sae activations have shape: {sae_acts.shape}')

The input to the SAE has shape: torch.Size([25000, 8192])
The SAE weight (W) has shape: torch.Size([8192, 65536])
The sae activations have shape: (25000, 65536)

### Inspect the feats np object

In [18]:
print(f'There are {len(sae_acts)} tokens in this sequence window.')
print(f'Each token has {len(layer_act[0])} features. This is the model hidden size or model dimension.')
print(f'Each token embedding was expanded to {sae_acts.shape[1]} features by the SAE.')

# convert to a dataframe
df_feats = pd.DataFrame(sae_acts, columns=[f'feature_{i}' for i in range(sae_acts.shape[1])])
df_feats.insert(0, 'base', list(sequence))
df_feats.insert(0, 'position', range(WINDOW_START, WINDOW_END + 1))
df_feats.head(10)

There are 25000 tokens in this sequence window.
Each token has 8192 features. This is the model hidden size or model dimension.
Each token embedding was expanded to 65536 features by the SAE.

,position,base,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,...,feature_65526,feature_65527,feature_65528,feature_65529,feature_65530,feature_65531,feature_65532,feature_65533,feature_65534,feature_65535
0,1,A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,T,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,T,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7,G,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8,T,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,T,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10,T,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Which features are most active?
# START HERE

In [ ]:
# Work directly with the numpy array instead of DataFrame
print(f"SAE activations shape: {sae_acts.shape}")
# Count non-zero per feature (column-wise) - vectorized
nonzero_per_feature = (sae_acts != 0).sum(axis=0)
# Get top 20 most active features
top_indices = np.argsort(nonzero_per_feature)[-20:][::-1]
top_counts = nonzero_per_feature[top_indices]
print("\nTop 20 most active features:")
for idx, count in zip(top_indices, top_counts):
    print(f"  feature_{idx}: {count}")

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_65526,feature_65527,feature_65528,feature_65529,feature_65530,feature_65531,feature_65532,feature_65533,feature_65534,feature_65535
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

feature_15721    25000
feature_40087    25000
feature_41367    25000
feature_60230    25000
feature_40575    25000
feature_57988    25000
feature_55126    25000
feature_25486    25000
feature_44637    25000
feature_28806    25000
feature_6288     25000
feature_34213    25000
feature_38461    25000
feature_16846    25000
feature_34425    25000
feature_13896    25000
feature_62365    25000
feature_60958    25000
feature_45495    25000
feature_53853    25000
dtype: int64

:

### Make a binary version of the feature data frame

In [20]:
# Make a binary version of the feature data frame
df_feats_binary = df_feats.copy()
for col in df_feats_binary.columns[2:]:  # exclude position, base
    df_feats_binary[col] = (df_feats_binary[col] != 0).astype(int)

df_feats_binary.head()

:

:

### Parse GFF and collect annotations in the 1..25,000 window

In [ ]:
# Minimal GFF parser: we keep rows overlapping our window on this chromosome.
def parse_gff_window(gff_path, target_seqid, start_1b, end_1b,
                     keep_types=None):
    if keep_types is None:
        keep_types = {"gene","CDS","exon","mRNA","ncRNA","tRNA","rRNA","misc_feature","Regulatory","tmRNA","mobile_element"}

    out = []
    with open(gff_path, "r", newline="") as fh:
        for line in fh:
            if not line or line.startswith("#"):
                continue
            parts = line.strip().split("	")
            if len(parts) < 9:
                continue
            seqid, source, ftype, start, end, score, strand, phase, attrs = parts
            if seqid != target_seqid:
                continue
            try:
                s = int(start); e = int(end)
            except:
                continue
            if e < start_1b or s > end_1b:
                continue
            if ftype not in keep_types:
                continue
            # Clip to window for plotting
            s_clipped = max(start_1b, s) - start_1b
            e_clipped = min(end_1b,   e) - start_1b
            out.append((s_clipped, e_clipped, ftype, strand, attrs))
    return out

# Try to match the sequence/chromosome name used in GFF to our chosen FASTA record
gff_seqid = chr1_rec.id
ann = parse_gff_window(GFF_PATH, gff_seqid, WINDOW_START, WINDOW_END)

print("Annotations kept:", len(ann))
print("First few:", ann[:5])

### Inspect the annotations

In [ ]:
# view annotations as a dataframe
df_ann = pd.DataFrame(ann, columns=["start", "end", "type", "strand", "attributes"])
df_ann

### Make a dataframe with columns for position, base, and each annotation as a binary value

In [ ]:
# get a list of possible annotation types
annotation_types = df_ann["type"].unique()

print("Annotation types present in the sampled sequence:", annotation_types)

# make a dataframe of zeros with columns for each annotation type
df_ann_binary = pd.DataFrame(0, index=df_feats_binary.index, columns=annotation_types)

# loop over the rows and set the corresponding positions to 1
for index, row in df_ann.iterrows():
    df_ann_binary.loc[row["start"]:row["end"], row["type"]] = 1
df_ann_binary.insert(0, 'base', list(sequence))
df_ann_binary.insert(0, 'position', range(WINDOW_START, WINDOW_END + 1))

display(df_ann_binary.iloc[1510:1530])

### Add annotations to the df_feats_binary dataframe

In [ ]:
# Add annotations to the df_feats_binary dataframe
df_feats_ann_binary = pd.concat([df_ann_binary, df_feats_binary], axis=1)

df_feats_ann_binary

### Analyze the correlations between the features and the annotations

In [ ]:
# get the annotation and feature columns
annotation_cols = df_ann_binary.columns[2:]  # exclude position, base
feature_cols = [col for col in df_feats_ann_binary.columns if col.startswith("feature_")]

# make simplified dataframes
annotations = df_feats_ann_binary[annotation_cols]
features = df_feats_ann_binary[feature_cols]

# dictionary to hold correlation results
correlation_results = {}

# loop over the annotation columns and compute correlation with each feature
for ann_col in annotation_cols:
    corr = features.corrwith(annotations[ann_col])  # computes correlation column-wise
    correlation_results[ann_col] = corr

corr_df = pd.DataFrame(correlation_results)

corr_df

### Find the features with the highest correlations to each annotation

In [ ]:
# Find the features with the highest correlations to each annotation
# loop over the annotation columns and get top correlated features
corr_df['gene'].sort_values(ascending=False)[:5]  # top 5 features correlated with 'gene' annotation

### Plot a handful of SAE features with GFF overlays

In [ ]:
sae_acts.shape

In [ ]:
annotation_cols

In [ ]:

# Choose a few feature indices to visualize (change to taste)
# selected_features = [15680, 28339, 1050, 25666]
selected_features = [15809, 302, 7703, 26750, 25852]

ANNOTATION_COLORS = {
    'CDS': 'lightyellow',
    'gene': 'lightgray', 
    'mobile_element': 'lightgreen',
    'misc_feature': 'khaki',
    'rRNA': '#7AC8AC',
    'tRNA': '#662D91',
    'ncRNA': 'white',
    'Regulatory': 'lightcoral',
    'tmRNA': 'salmon',
    'exon': 'lightblue',
    'mRNA': 'lavender'
}

T = sae_acts.shape[0]
fig, axes = plt.subplots(len(selected_features), 1, figsize=(24, 1.6*len(selected_features)), sharex=True)

for i, feat_id in enumerate(selected_features):
    ax = axes[i] if len(selected_features) > 1 else axes
    if feat_id >= sae_acts.shape[1]:
        ax.text(0.01, 0.5, f"Feature {feat_id} out of range", transform=ax.transAxes)
        continue
    ax.plot(sae_acts[:, feat_id], lw=0.7, label=f"feature {feat_id}", alpha=0.9)
    for s, e, ftype, strand, attrs in ann:
        ax.axvspan(s, e, color=ANNOTATION_COLORS.get(ftype, 'lightgray'), alpha=0.25)
    ax.set_xlim(0, T)
    ax.set_yticks([0, max(0.1, sae_acts[:, feat_id].max())])
    ax.legend(loc="upper right", frameon=False)

plt.xlabel("Position (bp) in 1..25,000 window")
plt.show()


### Tips / Next steps
- Change `SAE_LAYER_NAME` to probe different hidden layers.
- Adjust `selected_features` to scan for interesting peaks.
- Expand `WINDOW_END` or slide `WINDOW_START` to explore more of chromosome 1.
- Save `feats_np` and overlay other tracks (GC%, motif hits, etc.).